/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_afei_texturedemo_NativeRenderer */

#ifndef _Included_com_afei_texturedemo_NativeRenderer
#define _Included_com_afei_texturedemo_NativeRenderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_afei_texturedemo_NativeRenderer
 * Method:    glInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_afei_texturedemo_NativeRenderer_glInit
  (JNIEnv *, jobject);

/*
 * Class:     com_afei_texturedemo_NativeRenderer
 * Method:    glResize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_afei_texturedemo_NativeRenderer_glResize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_afei_texturedemo_NativeRenderer
 * Method:    glDraw
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_afei_texturedemo_NativeRenderer_glDraw
  (JNIEnv *, jobject);

/*
 * Class:     com_afei_texturedemo_NativeRenderer
 * Method:    registerAssetManager
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_afei_texturedemo_NativeRenderer_registerAssetManager
        (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
